env:
  commonjs: true
  es6: true
  node: true
  jest/globals: true
plugins:
  - jest
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  'no-console' : 'off',
  'no-unused-vars' : 'warn'
}
